Repository HannahBibi/PracticePython, pull requests merged in 2019-01, with the labels that each got.

#88 Issue 82 - "Completed code and tests for the OrderBo issue 82, regarding postage costs and rates."
  CodingPractice/PythonAssignments/shoppingcart/bus/OrderBo.py
  CodingPractice/PythonAssignments/shoppingcart/dao/OrderJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/domain/OrderDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/bus/test_OrderBo.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/test_OrderJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/domain/test_OrderDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/resources/orders.json
  CodingPractice/PythonAssignments/tests/shoppingcart/resources/postage_matrix.py
Labels: enhancement

#91 Issue 89 - Changed postage calculation to use a dict.
  CodingPractice/PythonAssignments/shoppingcart/bus/OrderBo.py
  CodingPractice/PythonAssignments/tests/shoppingcart/bus/test_OrderBo.py
Labels: enhancement

#96 Issue 90 - Refactor shopping cart with an abstract PostageDao, as well as PostageJsonDao and a PostageDto.
  CodingPractice/PythonAssignments/shoppingcart/bus/OrderBo.py
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/domain/PostageRateDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/bus/test_OrderBo.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/test_PostageRateJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/domain/test_PostageRateDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/resources/postage_matrix.json
  CodingPractice/PythonAssignments/tests/shoppingcart/resources/postage_matrix.py
Labels: enhancement

#99 Issue 74 - Create a concrete CustomerPostgresDao
  .travis.yml
  CodingPractice/PythonAssignments/shoppingcart/bus/OrderBo.py
  CodingPractice/PythonAssignments/shoppingcart/dao/CustomerDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/ProductDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/CustomerJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/JsonFileReader.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/OrderJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/PostageRateJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/ProductJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/__init__.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/CustomerPostgresDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/ProductPostgresDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/__init__.py
  CodingPractice/PythonAssignments/shoppingcart/domain/CustomerDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/bus/test_OrderBoWithJsonDaos.py
  CodingPractice/PythonAssignments/tests/shoppingcart/bus/test_OrderBoWithMixedDaos.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/__init__.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_CustomerJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_OrderJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_PostageRateJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_ProductJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/__init__.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_CustomerPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_ProductPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/domain/test_CustomerDto.py
Labels: enhancement

#104 Issue 100 - Make PostageRatePostgresDao.
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateCache.py
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/PostageRateJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/shoppingcart/domain/PostageRateDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_PostageRateJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_CustomerPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/domain/test_PostageRateDto.py
  CodingPractice/PythonAssignments/tests/shoppingcart/resources/postage_matrix.json
Labels: enhancement

#106 Added code and tests for create_order on OrderPostgresDao
  CodingPractice/PythonAssignments/shoppingcart/dao/OrderDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/CustomerJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/MethodNotImplementedException.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/OrderJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/PostageRateJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/ProductJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/OrderPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_CustomerJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_OrderJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_OrderPostgresDao.py
Labels: enhancement

#108 Fixed test bugs so that empty PKs return None and other empty keys …
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_PostageRatePostgresDao.py
Labels: bug

#109 Issue 103 - Wrote delete_customer and update_customer on the CustomerPostgresDao and accompanying tests.
  CodingPractice/PythonAssignments/shoppingcart/dao/CustomerDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/CustomerJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/CustomerPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_CustomerJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_CustomerPostgresDao.py
Labels: enhancement

#114 Refactored the postgres tests to run faster, using setUpClass and tea…
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_CustomerPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_OrderPostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_ProductPostgresDao.py
Labels: enhancement

#115 issue_110: Wrote CRUD operations on PostageRatePostgresDao, and tests…
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/PostageRateJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_PostageRateJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_PostageRatePostgresDao.py
Labels: enhancement

#121 Discovered an issue with the cache updating, and will be fixed on ano…
  CodingPractice/PythonAssignments/shoppingcart/bus/OrderBo.py
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/json/PostageRateJsonDao.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/json/test_PostageRateJsonDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_PostageRatePostgresDao.py
Labels: enhancement

#122 Refactored PostageRatePostgresDao and tests to fix the cache bug
  CodingPractice/PythonAssignments/shoppingcart/dao/PostageRateCache.py
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/PostageRatePostgresDao.py
  CodingPractice/PythonAssignments/tests/shoppingcart/dao/postgres/test_PostageRatePostgresDao.py
Labels: bug

#125 issue_124: Make create_order easier to read
  CodingPractice/PythonAssignments/shoppingcart/dao/postgres/OrderPostgresDao.py
Labels: refactoring
